title:          "Your Name blog"
description:    "Musings of a Software Engineer."
url:            "https://afstonebharfon.github.io"
baseurl:        ""
author:         "Komla Afoutou"
email:          "afoutouk@msu.edu"

github_username:    afstonebharfon
twitter_username:   yourusername

markdown:       kramdown
highlighter:    rouge
permalink:      /:year/:month/:day/:title/

kramdown:
  input: GFM

plugins:
  - jekyll-feed

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - .gitignore